
stages:
  - build
  - test

build:
  stage: build
  script:
    - cd src/
    - make
    - cd ..
test:
  stage: test
  script:
    - cd src/
    - ./Test.exe > ../Pipeline/TestResults
    - cd ../Pipeline/
    - python check.py
